spring.application.name=student-management-system

spring.datasource.url=jdbc:postgresql://localhost:5433/student_management_db
spring.datasource.username=postgres
spring.datasource.password=Ahsen

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

server.port=8080

jwt.secret=mysecretkeymysecretkeymysecretkey12
jwt.expiration=3600000